language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: I8u19hBOrBB9Z1NcBZ7CgazUF5mgkN2XKSDfWM1Ae4+9yo0cjYFGtnfJttv6nGbFfzEdhfE2JcoyfIOyo1C2mvrnQo4voKkwMmoqPLLWz6YAuHt66pm21mMb0N0uIl4h+5CsJKfK8q7F1hpamEwNwFyrghRbO7MJ9tjgsfoO9uae+hJpbuR1HQQ4YGVWzNvGVLUU1oUDjUInAmL0gWloKiVDxogzreptRdH0K6+eSUaNCqJtVXNRufM2M9Xlc4Lk9LwpWONZDVIM4cbdDs8Fp0mo0v/RW8Amod/9Pf4jdXJidrG4a6Xx0bIpdOQPCgdjApPluLsUWKc/6p7Aw4cHrYA5ttuB1/8VgFK12W7nFalqute4BpHQ+vAuRdG/+vqWGFbXiH/GnPaiQ+HCOGrddvRYtZu85j0AyM4YyCOvSUc8/PZfoVP+wIVhydN9kwP9kVskYib1sBhUhSgvUJAuVOJ0a9r/LvvtO8xPRv1X2q8moBeWbYzZ0YnuHpCsHkXZLbcmljRXX1JHa4IcWuXlouBl/xZC2Shwzj2OXQqCh8rHpZT5WPCzznZRkdeqTpBKKegJWPuDXJ1M2MEBSy8twrJIGoEALLkiODxVCz3z3ew4ETOnkATeqE70msrom0d9V8R1bLnIuZCOkFQ7j0L3CIVOlZyI8IoVDL9165RlJyo=
  app: infinite-gorge-50352